//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Web.MyFatoorahServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MerchantDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MerchantDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchant_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchant_usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchant_passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchant_ReferenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchant_error_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string merchant_code {
            get {
                return this.merchant_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.merchant_codeField, value) != true)) {
                    this.merchant_codeField = value;
                    this.RaisePropertyChanged("merchant_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string merchant_username {
            get {
                return this.merchant_usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.merchant_usernameField, value) != true)) {
                    this.merchant_usernameField = value;
                    this.RaisePropertyChanged("merchant_username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string merchant_password {
            get {
                return this.merchant_passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.merchant_passwordField, value) != true)) {
                    this.merchant_passwordField = value;
                    this.RaisePropertyChanged("merchant_password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string merchant_ReferenceID {
            get {
                return this.merchant_ReferenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.merchant_ReferenceIDField, value) != true)) {
                    this.merchant_ReferenceIDField = value;
                    this.RaisePropertyChanged("merchant_ReferenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReturnURL {
            get {
                return this.ReturnURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnURLField, value) != true)) {
                    this.ReturnURLField = value;
                    this.RaisePropertyChanged("ReturnURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string merchant_error_url {
            get {
                return this.merchant_error_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.merchant_error_urlField, value) != true)) {
                    this.merchant_error_urlField = value;
                    this.RaisePropertyChanged("merchant_error_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string udf1 {
            get {
                return this.udf1Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf1Field, value) != true)) {
                    this.udf1Field = value;
                    this.RaisePropertyChanged("udf1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string udf2 {
            get {
                return this.udf2Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf2Field, value) != true)) {
                    this.udf2Field = value;
                    this.RaisePropertyChanged("udf2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string udf3 {
            get {
                return this.udf3Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf3Field, value) != true)) {
                    this.udf3Field = value;
                    this.RaisePropertyChanged("udf3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string udf4 {
            get {
                return this.udf4Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf4Field, value) != true)) {
                    this.udf4Field = value;
                    this.RaisePropertyChanged("udf4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string udf5 {
            get {
                return this.udf5Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf5Field, value) != true)) {
                    this.udf5Field = value;
                    this.RaisePropertyChanged("udf5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayRequestDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PayRequestDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapIt.Web.MyFatoorahServiceReference.CustomerDC CustomerDCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapIt.Web.MyFatoorahServiceReference.MerchantDC MerchantDCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapIt.Web.MyFatoorahServiceReference.ProductDC[] lstProductDCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapIt.Web.MyFatoorahServiceReference.TotalDC totalDCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private MapIt.Web.MyFatoorahServiceReference.PaymentModeDC paymentModeDCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MapIt.Web.MyFatoorahServiceReference.CustomerDC CustomerDC {
            get {
                return this.CustomerDCField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerDCField, value) != true)) {
                    this.CustomerDCField = value;
                    this.RaisePropertyChanged("CustomerDC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MapIt.Web.MyFatoorahServiceReference.MerchantDC MerchantDC {
            get {
                return this.MerchantDCField;
            }
            set {
                if ((object.ReferenceEquals(this.MerchantDCField, value) != true)) {
                    this.MerchantDCField = value;
                    this.RaisePropertyChanged("MerchantDC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MapIt.Web.MyFatoorahServiceReference.ProductDC[] lstProductDC {
            get {
                return this.lstProductDCField;
            }
            set {
                if ((object.ReferenceEquals(this.lstProductDCField, value) != true)) {
                    this.lstProductDCField = value;
                    this.RaisePropertyChanged("lstProductDC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MapIt.Web.MyFatoorahServiceReference.TotalDC totalDC {
            get {
                return this.totalDCField;
            }
            set {
                if ((object.ReferenceEquals(this.totalDCField, value) != true)) {
                    this.totalDCField = value;
                    this.RaisePropertyChanged("totalDC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public MapIt.Web.MyFatoorahServiceReference.PaymentModeDC paymentModeDC {
            get {
                return this.paymentModeDCField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentModeDCField, value) != true)) {
                    this.paymentModeDCField = value;
                    this.RaisePropertyChanged("paymentModeDC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CustomerDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string civil_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvenueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApartmentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string civil_id {
            get {
                return this.civil_idField;
            }
            set {
                if ((object.ReferenceEquals(this.civil_idField, value) != true)) {
                    this.civil_idField = value;
                    this.RaisePropertyChanged("civil_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Block {
            get {
                return this.BlockField;
            }
            set {
                if ((object.ReferenceEquals(this.BlockField, value) != true)) {
                    this.BlockField = value;
                    this.RaisePropertyChanged("Block");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Avenue {
            get {
                return this.AvenueField;
            }
            set {
                if ((object.ReferenceEquals(this.AvenueField, value) != true)) {
                    this.AvenueField = value;
                    this.RaisePropertyChanged("Avenue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string Building {
            get {
                return this.BuildingField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingField, value) != true)) {
                    this.BuildingField = value;
                    this.RaisePropertyChanged("Building");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Floor {
            get {
                return this.FloorField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorField, value) != true)) {
                    this.FloorField = value;
                    this.RaisePropertyChanged("Floor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string Apartment {
            get {
                return this.ApartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.ApartmentField, value) != true)) {
                    this.ApartmentField = value;
                    this.RaisePropertyChanged("Apartment");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TotalDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TotalDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double subtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double subtotal {
            get {
                return this.subtotalField;
            }
            set {
                if ((this.subtotalField.Equals(value) != true)) {
                    this.subtotalField = value;
                    this.RaisePropertyChanged("subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentModeDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaymentModeDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paymentModeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string paymentMode {
            get {
                return this.paymentModeField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentModeField, value) != true)) {
                    this.paymentModeField = value;
                    this.RaisePropertyChanged("paymentMode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string product_nameField;
        
        private double unitPriceField;
        
        private int qtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string product_name {
            get {
                return this.product_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.product_nameField, value) != true)) {
                    this.product_nameField = value;
                    this.RaisePropertyChanged("product_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double unitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                if ((this.unitPriceField.Equals(value) != true)) {
                    this.unitPriceField = value;
                    this.RaisePropertyChanged("unitPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int qty {
            get {
                return this.qtyField;
            }
            set {
                if ((this.qtyField.Equals(value) != true)) {
                    this.qtyField = value;
                    this.RaisePropertyChanged("qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayResponseDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PayResponseDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string paymentURLField;
        
        private double net_amountField;
        
        private int invoiceNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string referenceID {
            get {
                return this.referenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.referenceIDField, value) != true)) {
                    this.referenceIDField = value;
                    this.RaisePropertyChanged("referenceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string paymentURL {
            get {
                return this.paymentURLField;
            }
            set {
                if ((object.ReferenceEquals(this.paymentURLField, value) != true)) {
                    this.paymentURLField = value;
                    this.RaisePropertyChanged("paymentURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double net_amount {
            get {
                return this.net_amountField;
            }
            set {
                if ((this.net_amountField.Equals(value) != true)) {
                    this.net_amountField = value;
                    this.RaisePropertyChanged("net_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int invoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                if ((this.invoiceNumberField.Equals(value) != true)) {
                    this.invoiceNumberField = value;
                    this.RaisePropertyChanged("invoiceNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrderStatusRequestDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class GetOrderStatusRequestDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchant_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchant_usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchant_passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenceIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string merchant_code {
            get {
                return this.merchant_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.merchant_codeField, value) != true)) {
                    this.merchant_codeField = value;
                    this.RaisePropertyChanged("merchant_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string merchant_username {
            get {
                return this.merchant_usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.merchant_usernameField, value) != true)) {
                    this.merchant_usernameField = value;
                    this.RaisePropertyChanged("merchant_username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string merchant_password {
            get {
                return this.merchant_passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.merchant_passwordField, value) != true)) {
                    this.merchant_passwordField = value;
                    this.RaisePropertyChanged("merchant_password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string referenceID {
            get {
                return this.referenceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.referenceIDField, value) != true)) {
                    this.referenceIDField = value;
                    this.RaisePropertyChanged("referenceID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatusResponseDC", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OrderStatusResponseDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayTxnIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        private double gross_amountField;
        
        private double net_amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RefIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string udf5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PayTxnID {
            get {
                return this.PayTxnIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PayTxnIDField, value) != true)) {
                    this.PayTxnIDField = value;
                    this.RaisePropertyChanged("PayTxnID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Paymode {
            get {
                return this.PaymodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymodeField, value) != true)) {
                    this.PaymodeField = value;
                    this.RaisePropertyChanged("Paymode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double gross_amount {
            get {
                return this.gross_amountField;
            }
            set {
                if ((this.gross_amountField.Equals(value) != true)) {
                    this.gross_amountField = value;
                    this.RaisePropertyChanged("gross_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double net_amount {
            get {
                return this.net_amountField;
            }
            set {
                if ((this.net_amountField.Equals(value) != true)) {
                    this.net_amountField = value;
                    this.RaisePropertyChanged("net_amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string AuthID {
            get {
                return this.AuthIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthIDField, value) != true)) {
                    this.AuthIDField = value;
                    this.RaisePropertyChanged("AuthID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string PostDate {
            get {
                return this.PostDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PostDateField, value) != true)) {
                    this.PostDateField = value;
                    this.RaisePropertyChanged("PostDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string TransID {
            get {
                return this.TransIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransIDField, value) != true)) {
                    this.TransIDField = value;
                    this.RaisePropertyChanged("TransID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string RefID {
            get {
                return this.RefIDField;
            }
            set {
                if ((object.ReferenceEquals(this.RefIDField, value) != true)) {
                    this.RefIDField = value;
                    this.RaisePropertyChanged("RefID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string OrderID {
            get {
                return this.OrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIDField, value) != true)) {
                    this.OrderIDField = value;
                    this.RaisePropertyChanged("OrderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string udf1 {
            get {
                return this.udf1Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf1Field, value) != true)) {
                    this.udf1Field = value;
                    this.RaisePropertyChanged("udf1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string udf2 {
            get {
                return this.udf2Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf2Field, value) != true)) {
                    this.udf2Field = value;
                    this.RaisePropertyChanged("udf2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string udf3 {
            get {
                return this.udf3Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf3Field, value) != true)) {
                    this.udf3Field = value;
                    this.RaisePropertyChanged("udf3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string udf4 {
            get {
                return this.udf4Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf4Field, value) != true)) {
                    this.udf4Field = value;
                    this.RaisePropertyChanged("udf4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string udf5 {
            get {
                return this.udf5Field;
            }
            set {
                if ((object.ReferenceEquals(this.udf5Field, value) != true)) {
                    this.udf5Field = value;
                    this.RaisePropertyChanged("udf5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyFatoorahServiceReference.PayGatewayServiceSoap")]
    public interface PayGatewayServiceSoap {
        
        // CODEGEN: Generating message contract since element name merchantDCResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/merchantDC", ReplyAction="*")]
        MapIt.Web.MyFatoorahServiceReference.merchantDCResponse merchantDC(MapIt.Web.MyFatoorahServiceReference.merchantDCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/merchantDC", ReplyAction="*")]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.merchantDCResponse> merchantDCAsync(MapIt.Web.MyFatoorahServiceReference.merchantDCRequest request);
        
        // CODEGEN: Generating message contract since element name PayRequestResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PayRequest", ReplyAction="*")]
        MapIt.Web.MyFatoorahServiceReference.PayRequestResponse PayRequest(MapIt.Web.MyFatoorahServiceReference.PayRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PayRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.PayRequestResponse> PayRequestAsync(MapIt.Web.MyFatoorahServiceReference.PayRequestRequest request);
        
        // CODEGEN: Generating message contract since element name PayResponseResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PayResponse", ReplyAction="*")]
        MapIt.Web.MyFatoorahServiceReference.PayResponseResponse PayResponse(MapIt.Web.MyFatoorahServiceReference.PayResponseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PayResponse", ReplyAction="*")]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.PayResponseResponse> PayResponseAsync(MapIt.Web.MyFatoorahServiceReference.PayResponseRequest request);
        
        // CODEGEN: Generating message contract since element name req from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentRequest", ReplyAction="*")]
        MapIt.Web.MyFatoorahServiceReference.PaymentRequestResponse PaymentRequest(MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaymentRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.PaymentRequestResponse> PaymentRequestAsync(MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequest request);
        
        // CODEGEN: Generating message contract since element name getOrderStatusRequestDC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderStatusRequest", ReplyAction="*")]
        MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestResponse GetOrderStatusRequest(MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderStatusRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestResponse> GetOrderStatusRequestAsync(MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class merchantDCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="merchantDC", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.merchantDCRequestBody Body;
        
        public merchantDCRequest() {
        }
        
        public merchantDCRequest(MapIt.Web.MyFatoorahServiceReference.merchantDCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class merchantDCRequestBody {
        
        public merchantDCRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class merchantDCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="merchantDCResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.merchantDCResponseBody Body;
        
        public merchantDCResponse() {
        }
        
        public merchantDCResponse(MapIt.Web.MyFatoorahServiceReference.merchantDCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class merchantDCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.MerchantDC merchantDCResult;
        
        public merchantDCResponseBody() {
        }
        
        public merchantDCResponseBody(MapIt.Web.MyFatoorahServiceReference.MerchantDC merchantDCResult) {
            this.merchantDCResult = merchantDCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayRequest", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PayRequestRequestBody Body;
        
        public PayRequestRequest() {
        }
        
        public PayRequestRequest(MapIt.Web.MyFatoorahServiceReference.PayRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PayRequestRequestBody {
        
        public PayRequestRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PayRequestResponseBody Body;
        
        public PayRequestResponse() {
        }
        
        public PayRequestResponse(MapIt.Web.MyFatoorahServiceReference.PayRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PayRequestDC PayRequestResult;
        
        public PayRequestResponseBody() {
        }
        
        public PayRequestResponseBody(MapIt.Web.MyFatoorahServiceReference.PayRequestDC PayRequestResult) {
            this.PayRequestResult = PayRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayResponseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PayResponseRequestBody Body;
        
        public PayResponseRequest() {
        }
        
        public PayResponseRequest(MapIt.Web.MyFatoorahServiceReference.PayResponseRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class PayResponseRequestBody {
        
        public PayResponseRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayResponseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayResponseResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PayResponseResponseBody Body;
        
        public PayResponseResponse() {
        }
        
        public PayResponseResponse(MapIt.Web.MyFatoorahServiceReference.PayResponseResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayResponseResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PayResponseDC PayResponseResult;
        
        public PayResponseResponseBody() {
        }
        
        public PayResponseResponseBody(MapIt.Web.MyFatoorahServiceReference.PayResponseDC PayResponseResult) {
            this.PayResponseResult = PayResponseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequest", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequestBody Body;
        
        public PaymentRequestRequest() {
        }
        
        public PaymentRequestRequest(MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PayRequestDC req;
        
        public PaymentRequestRequestBody() {
        }
        
        public PaymentRequestRequestBody(MapIt.Web.MyFatoorahServiceReference.PayRequestDC req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PaymentRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PaymentRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PaymentRequestResponseBody Body;
        
        public PaymentRequestResponse() {
        }
        
        public PaymentRequestResponse(MapIt.Web.MyFatoorahServiceReference.PaymentRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PaymentRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.PayResponseDC PaymentRequestResult;
        
        public PaymentRequestResponseBody() {
        }
        
        public PaymentRequestResponseBody(MapIt.Web.MyFatoorahServiceReference.PayResponseDC PaymentRequestResult) {
            this.PaymentRequestResult = PaymentRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatusRequest", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequestBody Body;
        
        public GetOrderStatusRequestRequest() {
        }
        
        public GetOrderStatusRequestRequest(MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderStatusRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestDC getOrderStatusRequestDC;
        
        public GetOrderStatusRequestRequestBody() {
        }
        
        public GetOrderStatusRequestRequestBody(MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestDC getOrderStatusRequestDC) {
            this.getOrderStatusRequestDC = getOrderStatusRequestDC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderStatusRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderStatusRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestResponseBody Body;
        
        public GetOrderStatusRequestResponse() {
        }
        
        public GetOrderStatusRequestResponse(MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderStatusRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MapIt.Web.MyFatoorahServiceReference.OrderStatusResponseDC GetOrderStatusRequestResult;
        
        public GetOrderStatusRequestResponseBody() {
        }
        
        public GetOrderStatusRequestResponseBody(MapIt.Web.MyFatoorahServiceReference.OrderStatusResponseDC GetOrderStatusRequestResult) {
            this.GetOrderStatusRequestResult = GetOrderStatusRequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PayGatewayServiceSoapChannel : MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PayGatewayServiceSoapClient : System.ServiceModel.ClientBase<MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap>, MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap {
        
        public PayGatewayServiceSoapClient() {
        }
        
        public PayGatewayServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PayGatewayServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayGatewayServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PayGatewayServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapIt.Web.MyFatoorahServiceReference.merchantDCResponse MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.merchantDC(MapIt.Web.MyFatoorahServiceReference.merchantDCRequest request) {
            return base.Channel.merchantDC(request);
        }
        
        public MapIt.Web.MyFatoorahServiceReference.MerchantDC merchantDC() {
            MapIt.Web.MyFatoorahServiceReference.merchantDCRequest inValue = new MapIt.Web.MyFatoorahServiceReference.merchantDCRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.merchantDCRequestBody();
            MapIt.Web.MyFatoorahServiceReference.merchantDCResponse retVal = ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).merchantDC(inValue);
            return retVal.Body.merchantDCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.merchantDCResponse> MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.merchantDCAsync(MapIt.Web.MyFatoorahServiceReference.merchantDCRequest request) {
            return base.Channel.merchantDCAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.merchantDCResponse> merchantDCAsync() {
            MapIt.Web.MyFatoorahServiceReference.merchantDCRequest inValue = new MapIt.Web.MyFatoorahServiceReference.merchantDCRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.merchantDCRequestBody();
            return ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).merchantDCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapIt.Web.MyFatoorahServiceReference.PayRequestResponse MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.PayRequest(MapIt.Web.MyFatoorahServiceReference.PayRequestRequest request) {
            return base.Channel.PayRequest(request);
        }
        
        public MapIt.Web.MyFatoorahServiceReference.PayRequestDC PayRequest() {
            MapIt.Web.MyFatoorahServiceReference.PayRequestRequest inValue = new MapIt.Web.MyFatoorahServiceReference.PayRequestRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.PayRequestRequestBody();
            MapIt.Web.MyFatoorahServiceReference.PayRequestResponse retVal = ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).PayRequest(inValue);
            return retVal.Body.PayRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.PayRequestResponse> MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.PayRequestAsync(MapIt.Web.MyFatoorahServiceReference.PayRequestRequest request) {
            return base.Channel.PayRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.PayRequestResponse> PayRequestAsync() {
            MapIt.Web.MyFatoorahServiceReference.PayRequestRequest inValue = new MapIt.Web.MyFatoorahServiceReference.PayRequestRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.PayRequestRequestBody();
            return ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).PayRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapIt.Web.MyFatoorahServiceReference.PayResponseResponse MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.PayResponse(MapIt.Web.MyFatoorahServiceReference.PayResponseRequest request) {
            return base.Channel.PayResponse(request);
        }
        
        public MapIt.Web.MyFatoorahServiceReference.PayResponseDC PayResponse() {
            MapIt.Web.MyFatoorahServiceReference.PayResponseRequest inValue = new MapIt.Web.MyFatoorahServiceReference.PayResponseRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.PayResponseRequestBody();
            MapIt.Web.MyFatoorahServiceReference.PayResponseResponse retVal = ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).PayResponse(inValue);
            return retVal.Body.PayResponseResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.PayResponseResponse> MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.PayResponseAsync(MapIt.Web.MyFatoorahServiceReference.PayResponseRequest request) {
            return base.Channel.PayResponseAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.PayResponseResponse> PayResponseAsync() {
            MapIt.Web.MyFatoorahServiceReference.PayResponseRequest inValue = new MapIt.Web.MyFatoorahServiceReference.PayResponseRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.PayResponseRequestBody();
            return ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).PayResponseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapIt.Web.MyFatoorahServiceReference.PaymentRequestResponse MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.PaymentRequest(MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequest request) {
            return base.Channel.PaymentRequest(request);
        }
        
        public MapIt.Web.MyFatoorahServiceReference.PayResponseDC PaymentRequest(MapIt.Web.MyFatoorahServiceReference.PayRequestDC req) {
            MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequest inValue = new MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequestBody();
            inValue.Body.req = req;
            MapIt.Web.MyFatoorahServiceReference.PaymentRequestResponse retVal = ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).PaymentRequest(inValue);
            return retVal.Body.PaymentRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.PaymentRequestResponse> MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.PaymentRequestAsync(MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequest request) {
            return base.Channel.PaymentRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.PaymentRequestResponse> PaymentRequestAsync(MapIt.Web.MyFatoorahServiceReference.PayRequestDC req) {
            MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequest inValue = new MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.PaymentRequestRequestBody();
            inValue.Body.req = req;
            return ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).PaymentRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestResponse MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.GetOrderStatusRequest(MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequest request) {
            return base.Channel.GetOrderStatusRequest(request);
        }
        
        public MapIt.Web.MyFatoorahServiceReference.OrderStatusResponseDC GetOrderStatusRequest(MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestDC getOrderStatusRequestDC) {
            MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequest inValue = new MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequestBody();
            inValue.Body.getOrderStatusRequestDC = getOrderStatusRequestDC;
            MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestResponse retVal = ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).GetOrderStatusRequest(inValue);
            return retVal.Body.GetOrderStatusRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestResponse> MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap.GetOrderStatusRequestAsync(MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequest request) {
            return base.Channel.GetOrderStatusRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestResponse> GetOrderStatusRequestAsync(MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestDC getOrderStatusRequestDC) {
            MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequest inValue = new MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequest();
            inValue.Body = new MapIt.Web.MyFatoorahServiceReference.GetOrderStatusRequestRequestBody();
            inValue.Body.getOrderStatusRequestDC = getOrderStatusRequestDC;
            return ((MapIt.Web.MyFatoorahServiceReference.PayGatewayServiceSoap)(this)).GetOrderStatusRequestAsync(inValue);
        }
    }
}
