//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Broker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Broker()
        {
            this.BrokerAreas = new HashSet<BrokerArea>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public string FullNameEN { get; set; }
        public int CityId { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Link { get; set; }
        public string DetailsEN { get; set; }
        public string DetailsAR { get; set; }
        public string Photo { get; set; }
        public bool AllAreas { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> AdminUserId { get; set; }
        public Nullable<long> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrokerArea> BrokerAreas { get; set; }
        public virtual City City { get; set; }
    }
}
