//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContentPage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContentPage()
        {
            this.SubContentPages = new HashSet<ContentPage>();
            this.PageShows = new HashSet<PageShow>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string TitleEN { get; set; }
        public string TitleAR { get; set; }
        public bool HasLink { get; set; }
        public string Link { get; set; }
        public string ContentEN { get; set; }
        public string ContentAR { get; set; }
        public int Ordering { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> AdminUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentPage> SubContentPages { get; set; }
        public virtual ContentPage MainContentPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PageShow> PageShows { get; set; }
    }
}
