//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicesToken
    {
        public int Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public string DeviceId { get; set; }
        public string DeviceToken { get; set; }
        public int DeviceType { get; set; }
        public int PushCounter { get; set; }
        public bool IsLogged { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
