//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<int> GenNotifId { get; set; }
        public Nullable<long> PropertyId { get; set; }
        public Nullable<long> ServiceId { get; set; }
        public Nullable<int> OfferId { get; set; }
        public int TypeId { get; set; }
        public string TitleEN { get; set; }
        public string TitleAR { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        public virtual NotifType NotifType { get; set; }
        public virtual Offer Offer { get; set; }
        public virtual GenNotif GenNotif { get; set; }
        public virtual User User { get; set; }
        public virtual Property Property { get; set; }
        public virtual Service Service { get; set; }
    }
}
