//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransaction
    {
        public long Id { get; set; }
        public long CreditId { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentId { get; set; }
        public string TranId { get; set; }
        public string RefId { get; set; }
        public string Auth { get; set; }
        public string Result { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> PaidOn { get; set; }
    
        public virtual UserCredit UserCredit { get; set; }
    }
}
