//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyComponents = new HashSet<PropertyComponent>();
            this.PropertyFavorites = new HashSet<PropertyFavorite>();
            this.PropertyFeatures = new HashSet<PropertyFeature>();
            this.PropertyPhotos = new HashSet<PropertyPhoto>();
            this.PropertyVideos = new HashSet<PropertyVideo>();
            this.PropertyViews = new HashSet<PropertyView>();
            this.PropertyComments = new HashSet<PropertyComment>();
            this.Notifications = new HashSet<Notification>();
            this.PropertyReports = new HashSet<PropertyReport>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public int PurposeId { get; set; }
        public int TypeId { get; set; }
        public int CountryId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<double> Area { get; set; }
        public Nullable<int> BuildingAge { get; set; }
        public Nullable<double> MonthlyIncome { get; set; }
        public Nullable<double> SellingPrice { get; set; }
        public Nullable<double> RentPrice { get; set; }
        public string Details { get; set; }
        public string OtherPhones { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string Street { get; set; }
        public string PortalAddressEN { get; set; }
        public string PortalAddressAR { get; set; }
        public string PACI { get; set; }
        public int ViewersCount { get; set; }
        public bool PaySpecial { get; set; }
        public bool PayVideo { get; set; }
        public bool IsSpecial { get; set; }
        public bool IsAvailable { get; set; }
        public bool IsActive { get; set; }
        public bool AdminAdded { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> AdminUserId { get; set; }
    
        public virtual Block Block { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyComponent> PropertyComponents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyFavorite> PropertyFavorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyFeature> PropertyFeatures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyPhoto> PropertyPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyVideo> PropertyVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyView> PropertyViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyComment> PropertyComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyReport> PropertyReports { get; set; }
        public virtual User User { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual Purpos Purpos { get; set; }
    }
}
