//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ServiceAreas = new HashSet<ServiceArea>();
            this.ServiceFavorites = new HashSet<ServiceFavorite>();
            this.ServicePhotos = new HashSet<ServicePhoto>();
            this.ServiceRates = new HashSet<ServiceRate>();
            this.ServiceViews = new HashSet<ServiceView>();
            this.ServiceComments = new HashSet<ServiceComment>();
            this.Notifications = new HashSet<Notification>();
            this.ServiceReports = new HashSet<ServiceReport>();
        }
    
        public long Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public long UserId { get; set; }
        public int CityId { get; set; }
        public int CategoryId { get; set; }
        public int ExYears { get; set; }
        public string OtherPhones { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public int ViewersCount { get; set; }
        public bool AllAreas { get; set; }
        public bool IsCompany { get; set; }
        public bool IsSpecial { get; set; }
        public bool IsActive { get; set; }
        public bool AdminAdded { get; set; }
        public Nullable<int> Ordering { get; set; }
        public System.DateTime AddedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> AdminUserId { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceArea> ServiceAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceFavorite> ServiceFavorites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePhoto> ServicePhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRate> ServiceRates { get; set; }
        public virtual ServicesCategory ServicesCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceView> ServiceViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceComment> ServiceComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notification> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceReport> ServiceReports { get; set; }
        public virtual User User { get; set; }
    }
}
