//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechMessage
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string Sender { get; set; }
        public string TextMessage { get; set; }
        public bool IsRead { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
