//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBalanceLog
    {
        public long Id { get; set; }
        public string LogNo { get; set; }
        public long UserId { get; set; }
        public double Amount { get; set; }
        public string TransType { get; set; }
        public System.DateTime TransOn { get; set; }
    
        public virtual User User { get; set; }
    }
}
