//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapIt.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WatchList
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<int> PurposeId { get; set; }
        public System.DateTime AddedOn { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual Purpos Purpos { get; set; }
        public virtual User User { get; set; }
    }
}
